export const GITHUB_MEMBERS = [
  { githubUser: "alexskapene" },
  { githubUser: "RobertKule" },
  { githubUser: "alexdev-3" },
  { githubUser: "ardinbig" },
  { githubUser: "AshDest" },
  { githubUser: "Baraka24" },
  { githubUser: "bienvenuushindi" },
  { githubUser: "Cedric921" },
  { githubUser: "Tacite243" },
  { githubUser: "davidkathoh" },
  { githubUser: "Dieumerci-M2" },
  { githubUser: "djanielie" },
  { githubUser: "DoddyMatabaro" },
  { githubUser: "espoirMur" },
  { githubUser: "guillainbisimwa" },
  { githubUser: "henochit" },
  { githubUser: "herilion" },
  { githubUser: "hermanngumbu" },
  { githubUser: "JackMutobu" },
  { githubUser: "ESPOIRMITIMITI" },
  { githubUser: "barakadanny" },
  { githubUser: "landbit" },
] as const
